name: approve

on:
  workflow_call:
    secrets:
      token:
        description: 'GitHub token'
        required: false

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Approve PR if all required checks passed
    timeout-minutes: 5
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.token }}
