on:
  pull_request:

jobs:
  pre-commit:
    uses: cachuperia/github-reusable-workflows/.github/workflows/pre-commit.yml@v1.0.1

  commitlint:
    uses: cachuperia/github-reusable-workflows/.github/workflows/commitlint.yml@v1.0.1

  approve:
    if: ${{ success() }}
    needs:
      - pre-commit
      - commitlint
    uses: cachuperia/github-reusable-workflows/.github/workflows/approve.yml@v1.0.1
    secrets:
      token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}

#  debug-default:
#    uses: cachuperia/github-reusable-workflows/.github/workflows/debug.yml@DD-590-fix
#
#  debug-false:
#    uses: cachuperia/github-reusable-workflows/.github/workflows/debug.yml@DD-590-fix
#    with:
#      flag: false
#
#  debug-true:
#    uses: cachuperia/github-reusable-workflows/.github/workflows/debug.yml@DD-590-fix
#    with:
#      flag: true
