on:
  pull_request:

jobs:
  pre-commit:
    uses: agblox/github-reusable-workflows/.github/workflows/pre-commit.yml@DD-590-a
    with:
      python-version: '3.10.2'

  commitlint:
    uses: agblox/github-reusable-workflows/.github/workflows/commitlint.yml@DD-590-a

  approve:
    if: ${{ success() }}
    needs:
      - pre-commit
      - commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.ORG_MACHINE_USER_TOKEN }}"
