name: commitlint

on:
  workflow_call:
    inputs:
      workspace_path:
        required: true
        type: string

jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install commitlint-plugin-function-rules
      - uses: wagoid/commitlint-github-action@v3
        env:
          NODE_PATH: ${{ inputs.workspace_path }}/node_modules
