name: commitlint

on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Check PR commit messages with commitlint
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
      - run: npm install commitlint-plugin-function-rules --legacy-peer-deps
      - uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
