name: commitlint

on:
  workflow_call:
    inputs:
      node-version:
        default: '16.15.1'
        description: Node runtime version
        required: false
        type: string

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Check PR commit messages with commitlint
    timeout-minutes: 5
    steps:
      - name: Set up Node ${{ inputs.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ inputs.node-version }}
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - run: npm install commitlint-plugin-function-rules --legacy-peer-deps
      - uses: wagoid/commitlint-github-action@v5.3.1
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
