name: pre-commit

on:
  workflow_call:
    inputs:
      python-version:
        default: '3.8'
        description: 'Python runtime version'
        required: false
        type: string
      asdf:
        default: false
        description: Install asdf and plugins if true
        required: false
        type: boolean

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Check all files with pre-commit
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
        if: inputs.asdf
      - name: Install asdf plugins
        if: inputs.asdf
        run: |
          asdf plugin-add github-cli https://github.com/bartlomiejdanek/asdf-github-cli.git
          asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git
          asdf plugin-add terragrunt https://github.com/ohmer/asdf-terragrunt
          asdf plugin-add terraform-docs https://github.com/looztra/asdf-terraform-docs
          asdf plugin-add tflint https://github.com/skyzyx/asdf-tflint
          asdf plugin-add sops https://github.com/feniix/asdf-sops.git
          asdf install
          asdf current
      - name: Init tflint
        if: inputs.asdf
        shell: bash
        run: tflint --init
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - uses: pre-commit/action@v2.0.3
        env:
          SKIP: no-commit-to-branch
