name: pre-commit

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python runtime version'
        default: '3.8'
        required: false
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Check all files with pre-commit. Terraform edition
    timeout-minutes: 5
    env:
      SKIP: no-commit-to-branch
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/setup@v1
      - name: asdf install
        run: |
          asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git
          asdf plugin-add terraform-docs https://github.com/looztra/asdf-terraform-docs
          asdf plugin-add tflint https://github.com/skyzyx/asdf-tflint
          asdf install
          asdf current
      - name: Init tflint
        shell: bash
        run: tflint --init
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - uses: pre-commit/action@v2.0.3
