name: pre-commit

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python runtime version'
        default: '3.8'
        required: false
        type: string

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Run unit tests.
    steps:
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pip install poetry
      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true
      - name: Set up poetry cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            .venv
          key: poetry-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make bootstrap
      - name: Run unit tests
        run: make test
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
